### ISSUE TITLE
这个框架支持推送吗

### ISSUE THREAD

**Issue by yueswing07** [justjavac/flarum#10]
web的消息提醒 站内信的那种功能。

**Comment by justjavac** [comment]
支持，默认没有开启，使用的是 pusher.js

**Comment by yueswing07** [comment]
@justjavac   多谢解答   还想问下 ：
1. web的兼容新如何   
2. pusher.js 不了解 使用的什么技术啊 我了解的不多 是轮训 websock Server-Sent等？
3. 介绍说是php框架，不知道后台如何支持推送的？ 脚本也不能一直运行啊
以上理解不全和错误莫怪。

**Comment by justjavac** [comment]
第三方的推送服务
