### ISSUE TITLE
请问中文论坛还启用吗？

### ISSUE THREAD

**Issue by littlegolden** [justjavac/flarum#18]
打扰了，您好！我们这边有几个人想帮助您管理 Flarum 中文论坛，请问您有计划重启论坛吗？
这是我在 Flarum 的资料 https://discuss.flarum.org/u/Littlegolden

**Comment by justjavac** [comment]
flarum 开发速度太慢了，我已经弃坑了

**Comment by littlegolden** [comment]
啊。。。好吧，那大佬我们能替您拾起来吗？域名服务器费用我们出，我们会把中文站做好的！

**Comment by justjavac** [comment]
可以。搜 justjavac 加我微信吧
