### ISSUE TITLE
配置stmp(gmail)发送邮件

### ISSUE THREAD

**Issue by ztao165** [justjavac/flarum#7]
论坛都搭建好了，唯一的问题就是邮件服务怎么配置都不成功
刚开始我是用了网易的企业邮箱的smtp配置，但是一直提示500的错误
之后我又用了mailgun的配置，这个是可以的，但是需要升级帐号不然的话会有很多限制
最后我选择使用gmail的smtp服务，但是怎么配置都不成功
我在http://flarum.org.cn 注册了一个帐号，修改密码时发现可以收到邮件，而且发件人使用的是gmail的邮箱，想请教一下这个是怎么配置的
我的配置如下：
![image](https://cloud.githubusercontent.com/assets/9943135/26392073/db854138-4097-11e7-8175-3cc39a1e519d.png)

**Comment by justjavac** [comment]
Gmail 的有安全限制，配置完成后属于未知设备登录。

我也是使用的 Gmail。但是我注册了一个小号，并把安全设置将为了最低。

![tim 20170524154921](https://cloud.githubusercontent.com/assets/359395/26392276/995e8836-4098-11e7-9007-83f06605c561.png)

**Comment by ztao165** [comment]
好的，我试一下

**Comment by ztao165** [comment]
@justjavac 问题解决了，谢谢
